# Generated by Django 5.2.14 on 2026-05-12 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100, unique=True, verbose_name='Brinco/Nome')),
                ('raca', models.CharField(max_length=100, verbose_name='Raça')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoLeite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Coleta')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade (Litros)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='producao.animal')),
            ],
            options={
                'verbose_name': 'Produção de Leite',
                'verbose_name_plural': 'Produções de Leite',
            },
        ),
    ]
