# Generated by Django 5.2.14 on 2026-05-12 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producaoleite',
            options={},
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VAC', 'Vacinação'), ('PAR', 'Parto'), ('PRO', 'Queda de Produção'), ('CAR', 'Carência de Medicamento')], max_length=3)),
                ('mensagem', models.TextField()),
                ('data_alerta', models.DateField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.animal')),
            ],
        ),
        migrations.CreateModel(
            name='ControleReprodutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INS', 'Inseminação'), ('COB', 'Cobertura')], max_length=3)),
                ('data_evento', models.DateField()),
                ('diagnostico_gestacao', models.BooleanField(default=False)),
                ('previsao_parto', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(limit_choices_to={'sexo': 'F'}, on_delete=django.db.models.deletion.CASCADE, to='producao.animal')),
            ],
        ),
        migrations.CreateModel(
            name='ControleSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame_clinico', models.CharField(max_length=200)),
                ('ocorrencia_doenca', models.TextField(blank=True)),
                ('medidas_preventivas', models.TextField(blank=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=100)),
                ('dosagem', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('periodo_carencia_dias', models.IntegerField(help_text='Dias sem poder consumir o leite')),
                ('data_fim_carencia', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.animal')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('ADM', 'Administrador'), ('VET', 'Veterinário'), ('OPE', 'Operador')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vacina', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('data_aplicacao', models.DateField()),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.animal')),
            ],
        ),
    ]
