# Generated by Django 5.2.14 on 2026-05-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_alter_producaoleite_options_alerta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producaoleite',
            name='periodo',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde')], default='M', max_length=1, verbose_name='Período'),
        ),
    ]
