# Generated by Django 5.2.14 on 2026-05-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_producaoleite_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlesanitario',
            name='dias_carencia',
            field=models.IntegerField(default=0, verbose_name='Dias de Carência'),
        ),
        migrations.AddField(
            model_name='controlesanitario',
            name='tem_carencia',
            field=models.BooleanField(default=False, verbose_name='Possui Carência?'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tem_carencia',
            field=models.BooleanField(default=True, verbose_name='Possui Carência?'),
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='dias_carencia',
            field=models.IntegerField(default=0, verbose_name='Dias de Carência'),
        ),
        migrations.AddField(
            model_name='vacinacao',
            name='tem_carencia',
            field=models.BooleanField(default=False, verbose_name='Possui Carência?'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('VAC', 'Vacinação'), ('PAR', 'Parto'), ('PRO', 'Queda de Produção'), ('CAR', 'Carência'), ('SAN', 'Sanitário')], max_length=3),
        ),
        migrations.AlterField(
            model_name='controlesanitario',
            name='data_registro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='data_fim_carencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='periodo_carencia_dias',
            field=models.IntegerField(default=0, help_text='Dias sem poder consumir o leite'),
        ),
    ]
