# Generated by Django 5.2.12 on 2026-06-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_controlesanitario_dias_carencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='controle_sanitario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='producao.controlesanitario'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='producao.medicamento'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='vacinacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='producao.vacinacao'),
        ),
    ]
