# Generated by Django 6.0.6 on 2026-06-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_alerta_controle_sanitario_alerta_medicamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('proprietario', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=300)),
                ('tamanho_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('contato', models.CharField(max_length=100)),
                ('tipo_produto', models.CharField(help_text='Ex: Rações, Medicamentos, Equipamentos', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='controle_sanitario',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='vacinacao',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.fornecedor'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='producao.fazenda')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='producao.lote'),
        ),
    ]
